import "../globals.css";

import { Inter } from "next/font/google";
import type { Metadata } from "next";
import { ThemeProvider } from "@/src/theme/ThemeProvider";
import clsx from "clsx";
import { StoreProvider } from "@/src/store/store-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <StoreProvider>
      <html lang="en" className="h-full">
        <body className={clsx(inter.className, "bg-background h-full")}>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            {/* <Navbar /> */}
            {children}
          </ThemeProvider>
        </body>
      </html>
    </StoreProvider>
  );
}
